baseURL = 'https://sober.fyi'
languageCode = 'en-us'
title = 'SOBER'
theme = 'PaperMod'

[params]
    env = "production"
    description = "Elite DevOps & Platform Engineering. Stability through observability."

    [params.profileMode]
    enabled = true
    title = " " # Leave empty if the logo already says SOBER
    subtitle = "Systems Oriented Business Engineering & Research. <br/> **Eliminating technical volatility.**"
    imageUrl = "images/owl-mascot.svg"
    imageWidth = 120
    imageHeight = 120

    [params.assets]
        disableHLJS = false
        customCSS = ["static/css/tokyonight.css"]

    [[menu.main]]
        name = "Services"
        url = "/services"
        weight = 10
    [[menu.main]]
        name = "Philosophy"
        url = "/philosophy"
        weight = 20
